name: elliotderhay
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.0.12'
  webroot: public
  database: mysql:8.0
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  database:
    portforward: 49208
  node:
    type: node:16
    ports:
      - '3000:3000'
events:
  post-start:
    - appserver: php artisan db:seed
    - appserver: php artisan github:event:pull
    - appserver: php artisan tweet:pull
    - node: yarn dev
tooling:
  node:
    service: node
  npx:
    service: node
  pull_content:
    service: appserver
    description: pull fresh content from external sources
    cmd:
      - php artisan github:event:pull
      - php artisan tweet:pull
  refresh_db:
    service: appserver
    description: rebuild database with fresh data
    cmd:
      - php artisan migrate:refresh --seed
      - php artisan github:event:pull
      - php artisan tweet:pull
  yarn:
    service: node
