name: elliotderhay
recipe: laravel

config:
  php: '8.2'
  composer_version: 2
  webroot: public
  database: mysql:8.0

proxy:
  mail:
    - mail.elliotderhay.lndo.site
  pma:
    - pma.elliotderhay.lndo.site

services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install -y ca-certificates curl gnupg
      - mkdir -p /etc/apt/keyrings
      - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      - NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
      - apt-get update -y
      - apt-get install -y cron nodejs
      - npm install --location=global yarn
    run_as_root:
      - service cron start
    build:
      - yarn
    run:
      - crontab /app/config/local/cron
    xdebug: true
    config:
      php: /app/config/local/php.ini
    ssl: true
    ports:
      - '24690:24690'
      - '24691:24691'
      - '24692:24692'

  mail:
    type: mailhog
    ssl: true
    hogfrom:
      - appserver

  pma:
    type: phpmyadmin
    ssl: true
    hosts:
      - database

events:
  post-start:
    - printf "\033[0;31mDon't forget to run migrations and seed db!\033[0m\n"

tooling:
  node:
    service: appserver

  npx:
    service: appserver

  pull_content:
    service: appserver
    description: pull fresh content from external sources
    cmd:
      - php artisan github:event:pull
      - php artisan tweet:pull

  refresh_db:
    service: appserver
    description: rebuild database with fresh data
    cmd:
      - php artisan migrate:refresh --seed
      - php artisan github:event:pull
      - php artisan tweet:pull

  yarn:
    service: appserver

  dev:
    service: appserver
    description: Start vite dev server
    user: root
    cmd: yarn dev
