<div @class([
	'wheel',
	'mirrored' => $mirror,
	'fixed',
	'size-20',
	'bg-conic-270',
	'from-big-stone-800',
	'via-blue-200',
	'to-big-stone-800',
	'rounded-full',
	'left-3' => !$mirror,
	'right-3' => $mirror,
	'-bottom-10',
	'z-10',
	'-scale-x-100' => $mirror,
]) class=''></div>
