version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: 'develop'
    versioning-strategy: lockfile-only
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    target-branch: 'develop'
    versioning-strategy: lockfile-only
    labels:
      - dependencies