# largely based on Laravel's own tests.yml workflow
# Node + PNPM sections pulled from PNPM's CI docs: https://pnpm.io/continuous-integration#github-actions

name: Tests
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: ctype, curl, dom, fileinfo, filter, hash, libxml, mbstring, openssl, pcntl, pcre, pdo, pdo_sqlite, readline, session, sodium, sqlite, tokenizer, xml, zip
          coverage: none

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy testing environment file
        run: cp .env.testing .env

      - name: Install PNPM dependencies
        run: pnpm install

      - name: Run composer test script
        run: composer test